overrides:
  cookie@<0.7.0: ^0.7.0
  vite: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
